notifications:
  email: false
language: python
# enable 3.8 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.8
      dist: xenial
      sudo: true
install: "pip install -r dev-requirements.txt"
script:
  - ./run-all-tests.sh
