version: 0.2
phases:
  install:
    commands:
      - chmod -R 755 ./scripts/codebuild/*
      - ./scripts/codebuild/install.sh
  pre_build:
    commands:
      - ./scripts/codebuild/pre_build.sh
  build:
    commands:
      - ./scripts/codebuild/build.sh
  post_build:
    commands:
      - ./scripts/codebuild/post_build.sh

##################################
# Build Artifacts to be uploaded #
##################################

artifacts:
  files:
    # list of local files relative to this build environment that will be added to the final artifact (zip)
    - output.yml
    - test-stack-configuration.json
    - prod-stack-configuration.json
