AWSTemplateFormatVersion: "2010-09-09"
Description: "Manifest Pipeline"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  Stage:
    Type: String
    Description: The deployed stage
  TemplateBucket:
    Type: String
    Description: Bucket this (and code) is deployed in
  TemplateFolder:
    Type: String
    Description: Location of template files
  Version:
    Type: String
    Description: The github version of this deployment

Outputs:
  StateMachine:
    Value: !Ref StateMachine

Resources:

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"

  IndexInputLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: json-from-csv/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python2.7
      Timeout: "25"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/indexInput.zip

  IndexInputLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${IndexInputLambdaFunction}
      RetentionInDays: 7

  ManifestLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: manifest-from-input-json/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python2.7
      Timeout: "25"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/manifest.zip

  ManifestLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ManifestLambdaFunction}
      RetentionInDays: 7

  PyramidGeneratorLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: pyramid-generator/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python2.7
      Timeout: "25"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/pyramid.zip

  ManifestLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ManifestLambdaFunction}
      RetentionInDays: 7

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  StateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Manifest Pipeline",
              "StartAt": "ProcessInput",
              "States": {
                "ProcessInput": {
                  "Type": "Task",
                  "Resource": "${indexInputLambdaArn}",
                  "Next": "ProcessManifest"
                },
                "ProcessManifest": {
                  "Type": "Task",
                  "Resource": "${manifestLambdaArn}",
                  "Next": "PyramidGenerator"
                },
                "PyramidGenerator": {
                  "Type": "Task",
                  "Resource": "arn:aws:states:::ecs:runTask.sync",
                  "Parameters": {
                    "Cluster": "qa-testing",
                    "Count": 1,
                    "LaunchType": "FARGATE",
                    "TaskDefinition": "qa_tests_task:10"
                  },
                  "End": true
                }
              }
            }
          - { indexInputLambdaArn: !GetAtt [ IndexInputLambdaFunction, Arn ], manifestLambdaArn: !GetAtt [ ManifestLambdaFunction, Arn ] }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
