AWSTemplateFormatVersion: "2010-09-09"
Description: "Manifest Pipeline"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  Stage:
    Type: String
    Description: The deployed stage
  TemplateBucket:
    Type: String
    Description: Bucket this (and code) is deployed in
  TemplateFolder:
    Type: String
    Description: Location of template files
  Version:
    Type: String
    Description: The github version of this deployment

Outputs:
  StateMachine:
    Value: !Ref StateMachine

  ProcessBucket:
    Value: !Ref ProcessBucket

Resources:
  ProcessBucket:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !ImportValue wse-web-logs
        LogFilePrefix: s3/manifest-pipeline/process/

  ManifestBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      LoggingConfiguration:
        DestinationBucketName: !ImportValue wse-web-logs
        LogFilePrefix: s3/manifest-pipeline/
      WebsiteConfiguration:
        IndexDocument: index.json
        ErrorDocument: index.json
      CorsConfiguration:
        CorsRules:
          - Id: DefaultCorsHeader
            AllowedHeaders:
              - Authorization
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ImageDerivativeCacheBucketPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                Effect: "Allow"
                Resource:
                  - !GetAtt ProcessBucket.Arn
                  - Fn::Join:
                      - ""
                      -
                        - !GetAtt ProcessBucket.Arn
                        - "/*"
                  - !GetAtt ManifestBucket.Arn
                  - Fn::Join:
                      - ""
                      -
                        - !GetAtt ManifestBucket.Arn
                        - "/*"


  IndexInputLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: json-from-csv/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python3.7
      Timeout: "25"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/indexInput.zip
      Environment:
        Variables:
          PROCESS_BUCKET: !Ref ProcessBucket
          MANIFEST_BUCKET: !Ref ManifestBucket

  IndexInputLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${IndexInputLambdaFunction}
      RetentionInDays: 7

  ManifestLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: manifest-from-input-json/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python3.7
      Timeout: "25"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/manifest.zip

  ManifestLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ManifestLambdaFunction}
      RetentionInDays: 7

  FinalizeLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: finalize/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python3.7
      Timeout: "25"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/finalize.zip
      Environment:
        Variables:
          PROCESS_BUCKET: !Ref ProcessBucket

  FinalizeLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FinalizeLambdaFunction}
      RetentionInDays: 7
 
  # PYRAMID GENERATOR PROCESSING
  PGCounterLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: pyramid-generator/pgcounter.counter
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: nodejs8.10
      Timeout: 120
      MemorySize: 256
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/pyramid.zip
      Environment:
        Variables:
          PROCESS_BUCKET: !Ref ProcessBucket

  PGCounterLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PGCounterLambdaFunction}
      RetentionInDays: 7

  PGIteratorLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: pyramid-generator/pgiterator.iterator
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: nodejs8.10
      Timeout: 120
      MemorySize: 256
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/pyramid.zip
      Environment:
        Variables:
          PROCESS_BUCKET: !Ref ProcessBucket

  PGIteratorLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PGIteratorLambdaFunction}
      RetentionInDays: 7

  PGImgProcLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: pyramid-generator/pgimgproc.processor
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: nodejs8.10
      Timeout: 120
      MemorySize: 256
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/pyramid.zip
      Environment:
        Variables:
          PROCESS_BUCKET: !Ref ProcessBucket

  PGImgProcLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PGImgProcLambdaFunction}
      RetentionInDays: 7

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  StateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Manifest Pipeline",
              "StartAt": "ProcessInput",
              "States": {
                "ProcessInput": {
                  "Type": "Task",
                  "Resource": "${indexInputLambdaArn}",
                  "Next": "ProcessManifest"
                },
                "ProcessManifest": {
                  "Type": "Task",
                  "Resource": "${manifestLambdaArn}",
                  "Next": "PGCount"
                },
                "PGCount": {
                  "Type": "Task",
                  "Resource": "${pgCountLambdaArn}",
                  "ResultPath": "$.data",
                  "Next": "PGIterator"
                },
                "PGIterator": {
                    "Type": "Task",
                    "Resource": "${pgIteratorLambdaArn}",
                    "ResultPath": "$.data",
                    "Next": "PGIsCountReached"
                },
                "PGIsCountReached": {
                    "Type": "Choice",
                    "Choices": [
                        {
                            "Variable": "$.data.iterator.continue",
                            "BooleanEquals": true,
                            "Next": "PGImgProcessor"
                        }
                    ],
                    "Default": "Finalize"
                },
                "PGImgProcessor": {
                    "Type": "Task",
                    "Resource": "${pgImgProcLambdaArn}",
                    "ResultPath": "$.data",
                    "Next": "PGIterator"
                },
                "Finalize": {
                  "Type": "Task",
                  "Resource": "${finalizeLambdaArn}",
                  "End": true
                }
              }
            }
          - { indexInputLambdaArn: !GetAtt [ IndexInputLambdaFunction, Arn ], manifestLambdaArn: !GetAtt [ ManifestLambdaFunction, Arn ], pgCountLambdaArn: !GetAtt [ PGCounterLambdaFunction, Arn], pgIteratorLambdaArn: !GetAtt [ PGIteratorLambdaFunction, Arn], pgImgProcLambdaArn: !GetAtt [ PGImgProcLambdaFunction, Arn], finalizeLambdaArn: !GetAtt [ FinalizeLambdaFunction, Arn ] }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
