AWSTemplateFormatVersion: "2010-09-09"
Description: "Manifest Pipeline"

Parameters:
  ServiceName:
    Type: String
    Description: The name of the service
  Stage:
    Type: String
    Description: The deployed stage
  TemplateBucket:
    Type: String
    Description: Bucket this (and code) is deployed in
  TemplateFolder:
    Type: String
    Description: Location of template files
  Version:
    Type: String
    Description: The github version of this deployment
  ImageSourceBucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The name of the source bucket that the IIIF Image service will read from for its assets.
    Default: '/all/stacks/mellon-data-broker-dev/publicbucket'
  ImageServerUrl:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: The url of the IIIF Image Server
    Default: '/all/stacks/mellon-image-service-dev/url'
  InfrastructureStackName:
    Type: String
    Default: "mellon-app-infrastructure"
    Description: The name of the parent infrastructure/networking stack that you created. Necessary
                 to locate and reference resources created by that stack.

Outputs:
  StateMachine:
    Value: !Ref StateMachine

  ProcessBucket:
    Value: !Ref ProcessBucket

  ManifestBucket:
    Value: !Ref ManifestBucket

Resources:
  CanvasDefaultWidth:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/canvas-default-width"
      Value: "2000"
      Description: Canvas default width

  CanvasDefaultHeight:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/canvas-default-height"
      Value: "2000"
      Description: Canvas default height

  ImageServerBaseUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/image-server-base-url"
      Value: "https://STUB:8182/iiif/2"
      Description: Image server base url

  MainCsv:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/main-csv"
      Value: "main.csv"
      Description: CSV name

  SequenceCsv:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/sequence-csv"
      Value: "sequence.csv"
      Description: CSV name

  ManifestServerBaseUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/manifest-server-base-url"
      Value: "https://"
      Description: CSV name

  ProcessBucketReadBasepath:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/process-bucket-read-basepath"
      Value: "process"
      Description: S3 bucket read base path

  ProcessBucketWriteBasepath:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/process-bucket-write-basepath"
      Value: "finished"
      Description: S3 bucket write base path

  ImageServerBucketBasepath:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/image-server-bucket-basepath"
      Value: "images"
      Description: S3 bucket images base path

  ManifestServerBucketBasepath:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/manifest-server-bucket-basepath"
      Value: "manifest"
      Description: S3 bucket images base path

  EventFile:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/all/stacks/mellon-manifest-pipeline/config/${Stage}/event-file"
      Value: "event.json"
      Description: S3 event filename

  ProcessBucket:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName:
          Fn::ImportValue: !Join [':', [!Ref InfrastructureStackName, 'LogBucket']]
        LogFilePrefix: s3/data-broker/

  ManifestBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      LoggingConfiguration:
        DestinationBucketName:
          Fn::ImportValue: !Join [':', [!Ref InfrastructureStackName, 'LogBucket']]
        LogFilePrefix: s3/data-broker/
      WebsiteConfiguration:
        IndexDocument: index.json
        ErrorDocument: index.json
      CorsConfiguration:
        CorsRules:
          - Id: DefaultCorsHeader
            AllowedHeaders:
              - Authorization
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: ManifestPipelineSsmPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Action:
                  - "ssm:GetParametersByPath"
                Effect: "Allow"
                Resource: "arn:aws:ssm:us-east-1:*:parameter/all/stacks/mellon-manifest*"
        - PolicyName: ImageDerivativeCacheBucketPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketVersions"
                  - "s3:PutObjectVersionAcl"
                  - "s3:PutObjectAcl"
                Effect: "Allow"
                Resource:
                  - !GetAtt ProcessBucket.Arn
                  - Fn::Join:
                      - ""
                      -
                        - !GetAtt ProcessBucket.Arn
                        - "/*"
                  - !GetAtt ManifestBucket.Arn
                  - Fn::Join:
                      - ""
                      -
                        - !GetAtt ManifestBucket.Arn
                        - "/*"
                  - Fn::Join:
                    - ""
                    -
                      - !Sub "arn:aws:s3:::"
                      - !Ref ImageSourceBucket
                  - Fn::Join:
                    - ""
                    -
                      - !Sub "arn:aws:s3:::"
                      - !Ref ImageSourceBucket
                      - "/*"


  IndexInputLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: json-from-csv/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python3.7
      Timeout: "25"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/indexInput.zip
      Environment:
        Variables:
          STAGE: !Ref Stage
          PROCESS_BUCKET: !Ref ProcessBucket
          MANIFEST_BUCKET: !Ref ManifestBucket
          IMAGE_BUCKET: !Ref ImageSourceBucket
          IMAGE_SERVER_URL: !Ref ImageServerUrl
          MANIFEST_URL:
            Fn::Join:
              - ""
              -
                - !Ref ManifestBucket
                - ".s3-website-us-east-1.amazonaws.com"

  IndexInputLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${IndexInputLambdaFunction}
      RetentionInDays: 7

  ManifestLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: manifest-from-input-json/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python3.7
      Timeout: "25"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/manifest.zip

  ManifestLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ManifestLambdaFunction}
      RetentionInDays: 7

  FinalizeLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: finalize/handler.run
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: python3.7
      Timeout: "300"
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/finalize.zip

  FinalizeLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FinalizeLambdaFunction}
      RetentionInDays: 7

  # PYRAMID GENERATOR PROCESSING
  PGCounterLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: pyramid-generator/pgcounter.counter
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: nodejs8.10
      Timeout: 120
      MemorySize: 256
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/pyramid.zip

  PGCounterLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PGCounterLambdaFunction}
      RetentionInDays: 7

  PGIteratorLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: pyramid-generator/pgiterator.iterator
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: nodejs8.10
      Timeout: 120
      MemorySize: 3008
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/pyramid.zip

  PGIteratorLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PGIteratorLambdaFunction}
      RetentionInDays: 7

  PGImgProcLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: pyramid-generator/pgimgproc.processor
      Role: !GetAtt [ LambdaExecutionRole, Arn ]
      Runtime: nodejs8.10
      Timeout: 120
      MemorySize: 256
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: !Sub ${TemplateFolder}/pyramid.zip

  PGImgProcLambdaFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PGImgProcLambdaFunction}
      RetentionInDays: 7

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  StateMachine:
    Type: "AWS::StepFunctions::StateMachine"
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Manifest Pipeline",
              "StartAt": "ProcessInput",
              "States": {
                "ProcessInput": {
                  "Type": "Task",
                  "Resource": "${indexInputLambdaArn}",
                  "Next": "ProcessManifest"
                },
                "ProcessManifest": {
                  "Type": "Task",
                  "Resource": "${manifestLambdaArn}",
                  "Next": "PGCount"
                },
                "PGCount": {
                  "Type": "Task",
                  "Resource": "${pgCountLambdaArn}",
                  "Next": "PGIterator"
                },
                "PGIterator": {
                    "Type": "Task",
                    "Resource": "${pgIteratorLambdaArn}",
                    "Next": "PGIsCountReached"
                },
                "PGIsCountReached": {
                    "Type": "Choice",
                    "Choices": [
                        {
                          "Variable": "$.pgimage.iterator.continue",
                            "BooleanEquals": true,
                            "Next": "PGImgProcessor"
                        }
                    ],
                    "Default": "Finalize"
                },
                "PGImgProcessor": {
                    "Type": "Task",
                    "Resource": "${pgImgProcLambdaArn}",
                    "Next": "PGIterator"
                },
                "Finalize": {
                  "Type": "Task",
                  "Resource": "${finalizeLambdaArn}",
                  "End": true
                }
              }
            }
          - { indexInputLambdaArn: !GetAtt [ IndexInputLambdaFunction, Arn ], manifestLambdaArn: !GetAtt [ ManifestLambdaFunction, Arn ], pgCountLambdaArn: !GetAtt [ PGCounterLambdaFunction, Arn], pgIteratorLambdaArn: !GetAtt [ PGIteratorLambdaFunction, Arn], pgImgProcLambdaArn: !GetAtt [ PGImgProcLambdaFunction, Arn], finalizeLambdaArn: !GetAtt [ FinalizeLambdaFunction, Arn ] }
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]
